minikura:
  hostname: php
  build: ./builds/php
  user: root
  ports:
    - "80:80"
  volumes:
    - /app:/var/www/html/
    - ./config/php/:/usr/local/etc/php/
  links:
    - smtp

smtp:
  build: ./builds/smtp
  ports:
    - "8080:1080"
